version: '3.8'

services:
  titanic-model-service:
    build:
      context: titanic_model_service
    image: titanic-model-service:latest
    volumes:
      - ./titanic_model_service:/app
    networks:
      - internal

  titanic-webapp-service:
    build:
      context: titanic_web_service
    ports:
      - "8080:80"
    depends_on:
      - titanic-model-service
      - reverse-proxy
    volumes:
      - ./titanic_web_service:/usr/share/nginx/html
    networks:
      - internal

  reverse-proxy:
    image: nginx:latest
    ports:
      - "5001:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - titanic-model-service
    networks:
      - internal

networks:
  internal:
    driver: bridge
